'use client';

import { ArrowDown, ArrowLeft, ArrowUp, Check, FileImage, ImagePlus, LayoutDashboard, LogOut, Save, ShieldCheck, Trash2, Users, Wrench } from 'lucide-react';
import Image from 'next/image';
import UsersPanel from '@/components/admin-users';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Switch } from '@/components/ui/switch';
import { canAccessAdmin } from '@/lib/access';
import { builtInServicePhotos, parseHiddenBuiltInPhotos, serviceOptions, serviceVisibilityKey, type ServiceSlug } from '@/lib/services';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type User = {id:string;email:string;name:string;role:'super_admin'|'admin'|'user';status:'active'|'disabled';googleConnected:boolean;createdAt:number};
type Data = {user:User;content:Array<{key:string;value_ka:string;value_en:string}>;settings:Array<{key:string;value:string}>;media:Array<{id:string;filename:string;content_type:string;size:number;alt_ka:string;alt_en:string;created_at:number;url:string;in_gallery:number;gallery:ServiceSlug|null;gallery_order:number|null}>};
const fields=[
  ['hero_title_a','მთავარი სათაური — პირველი ხაზი','Hero title — first line','ლითონს ვაძლევთ','We shape metal'],
  ['hero_title_b','მთავარი სათაური — მეორე ხაზი','Hero title — second line','ძლიერ ფორმას.','to last.'],
  ['hero_lead','მთავარი აღწერა','Hero description','ყველა ტიპის შედუღება, ელექტრო მომსახურება, ლაზერული ჭრა და ავტომობილის დიაგნოსტიკა — ერთი საიმედო გუნდისგან.','All types of welding, electrical services, laser cutting and basic car diagnostics — from one reliable team.'],
  ['welding_title','შედუღების სათაური','Welding heading','შედუღება, რომელიც უძლებს დროს','Welding built to stand the test of time'],
  ['welding_text','შედუღების აღწერა','Welding description','ვმუშაობთ როგორც კერძო შეკვეთებზე, ისე სამშენებლო კომპანიებისა და საწარმოებისთვის.','We handle private jobs as well as projects for construction companies and factories.'],
  ['services_title','სერვისების სათაური','Services heading','ყველა სერვისი ერთ სივრცეში','Every service in one place'],
  ['cta_title','კონტაქტის სათაური','Contact heading','გაქვთ სამუშაო? დავიწყოთ საუბარი.','Have a job in mind? Let’s talk.'],
  ['cta_text','კონტაქტის აღწერა','Contact description','გამოგვიგზავნეთ ფოტო ან მოკლე აღწერა WhatsApp-ზე და მიიღეთ სწრაფი პასუხი.','Send a photo or a short description on WhatsApp and get a quick response.'],
] as const;
const servicePhoneFields = [
  ['phone_welding', 'Welding phone / WhatsApp', '+995574814088'],
  ['phone_electrical', 'Electrical phone / WhatsApp', '568 88 41 35'],
  ['phone_laser_cutting', 'Laser cutting phone / WhatsApp', '568 88 41 35'],
  ['phone_excavator', 'Excavator service phone / WhatsApp', '+995574814088'],
  ['phone_towing', 'Towing service phone / WhatsApp', '+995574814088'],
  ['phone_diagnostics', 'Car diagnostics phone / WhatsApp', '568 88 41 35'],
] as const;
type AdminTab = 'content'|'services'|'media'|'users';

async function api<T=any>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const result:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Something went wrong.');return result as T;}

export default function AdminDashboard({initialTab='content'}:{initialTab?:AdminTab}){
  const [me,setMe]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<AdminTab>(initialTab);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setError('');try{const auth=await api<{user:User|null}>('/api/auth/me');if(!canAccessAdmin(auth.user)){setMe(null);setData(null);window.location.replace('/login');return;}setMe(auth.user);const admin=await api<Data>('/api/admin');setData(admin);}catch(e){setError(e instanceof Error?e.message:'Could not load admin panel.');}finally{setLoading(false);}},[]);
  useEffect(()=>{if(initialTab!=='users'){const requested=new URLSearchParams(window.location.search).get('tab');if(requested==='content'||requested==='services'||requested==='media')setTab(requested);}void load();},[load,initialTab]);
  const flash=(message:string)=>{setNotice(message);setTimeout(()=>setNotice(''),3000);};
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#090a0b] text-white"><div className="flex items-center gap-3"><Wrench className="animate-spin text-orange-500"/>Loading admin panel…</div></div>;
  if(!me)return <div className="grid min-h-screen place-items-center bg-[#090a0b] text-white"><a href="/login" className="text-orange-400">Log in to continue</a></div>;
  if(!data)return <div className="grid min-h-screen place-items-center bg-[#090a0b] p-6 text-center text-white"><div><p className="text-red-400">{error||'Could not load dashboard.'}</p><button onClick={load} className="mt-4 rounded-full bg-orange-500 px-6 py-3 font-bold text-black">Try again</button></div></div>;
  return <div className="min-h-screen bg-[#0a0b0d] text-white">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0a0b0d]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><Image src="/logo.jpg" width={46} height={46} alt="Napertskala" className="h-11 w-11 rounded-full object-cover"/><div><strong className="block">Napertskala</strong><span className="text-xs text-zinc-500">Content management</span></div></div><div className="flex items-center gap-3"><a href="/" className="hidden items-center gap-2 text-sm text-zinc-400 hover:text-white sm:flex"><ArrowLeft className="h-4 w-4"/>View site</a><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.replace('/');}} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-zinc-400 hover:text-white" aria-label="Log out"><LogOut className="h-4 w-4"/></button></div></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[260px_1fr]">
      <aside className="border-b border-white/10 p-4 lg:min-h-[calc(100vh-80px)] lg:border-b-0 lg:border-r lg:p-6"><div className="flex gap-2 overflow-x-auto lg:block lg:space-y-2">{([['content',LayoutDashboard,'Content','/admin'],['services',Wrench,'Services','/admin?tab=services'],['media',FileImage,'Images','/admin?tab=media'],['users',Users,'Users','/admin/users']] as const).filter(([id])=>id!=='users'||me.role==='super_admin').map(([id,Icon,label,href])=><a key={id} href={href} aria-current={tab===id?'page':undefined} className={`flex min-w-max items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold lg:w-full ${tab===id?'bg-orange-500 text-black':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-5 w-5"/>{label}</a>)}</div><div className="mt-8 hidden rounded-2xl border border-white/10 bg-white/[.03] p-4 lg:block"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-orange-500/15 text-orange-400"><ShieldCheck className="h-5 w-5"/></span><div className="min-w-0"><strong className="block truncate text-sm">{me.name}</strong><span className="text-xs text-zinc-500">{me.role==='super_admin'?'Super Admin':'Admin'}</span></div></div></div></aside>
      <main className="min-w-0 p-5 sm:p-8 lg:p-10">{notice&&<div className="fixed right-5 top-24 z-50 flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-black shadow-xl"><Check className="h-5 w-5"/>{notice}</div>}{error&&<div className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
        {tab==='content'&&<ContentPanel data={data} onSaved={async()=>{flash('Content saved');await load();}} onError={setError}/>} {tab==='services'&&<ServicesPanel data={data} onSaved={async(m)=>{flash(m);await load();}} onError={setError}/>} {tab==='media'&&<MediaPanel data={data} onSaved={async(m)=>{flash(m);await load();}} onError={setError}/>} {tab==='users'&&me.role==='super_admin'&&<UsersPanel/>}
      </main>
    </div>
  </div>;
}

function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="block"><span className="mb-2 block text-xs font-bold text-zinc-400">{label}</span><input required {...props} className="h-12 w-full rounded-xl border border-white/10 bg-black/30 px-4 outline-none transition focus:border-orange-500"/></label>}

function ServicesPanel({data,onSaved,onError}:{data:Data;onSaved:(message:string)=>Promise<void>;onError:(e:string)=>void}){
  const settings=useMemo(()=>Object.fromEntries(data.settings.map(item=>[item.key,item.value])),[data.settings]);
  const [enabled,setEnabled]=useState<Record<ServiceSlug,boolean>>(()=>Object.fromEntries(serviceOptions.map(service=>[service.slug,settings[serviceVisibilityKey(service.slug)]!=='false'])) as Record<ServiceSlug,boolean>);
  const [saving,setSaving]=useState<ServiceSlug|null>(null);
  useEffect(()=>{setEnabled(Object.fromEntries(serviceOptions.map(service=>[service.slug,settings[serviceVisibilityKey(service.slug)]!=='false'])) as Record<ServiceSlug,boolean>);},[settings]);
  async function toggle(slug:ServiceSlug,next:boolean){const service=serviceOptions.find(item=>item.slug===slug)!;const previous=enabled[slug];setEnabled(current=>({...current,[slug]:next}));setSaving(slug);onError('');try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values:{[serviceVisibilityKey(slug)]:next?'true':'false'}})});await onSaved(`${service.label} turned ${next?'on':'off'}`);}catch(err){setEnabled(current=>({...current,[slug]:previous}));onError(err instanceof Error?err.message:'Could not update service.');}finally{setSaving(null);}}
  return <><PanelTitle icon={Wrench} title="Services" text="Turn public services on or off. Each change is saved immediately."/><div className="mt-8 grid gap-4 xl:grid-cols-2">{serviceOptions.map(service=>{const isEnabled=enabled[service.slug];const isSaving=saving===service.slug;return <article key={service.slug} className={`rounded-2xl border p-5 transition ${isEnabled?'border-emerald-500/30 bg-emerald-500/[.06]':'border-white/10 bg-[#111214]'}`}><div className="flex items-center justify-between gap-5"><div className="min-w-0"><h2 className="text-lg font-black">{service.label}</h2><p className="mt-1 text-sm text-zinc-500">{service.labelKa}</p><div className="mt-4 flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-black ${isEnabled?'bg-emerald-500/15 text-emerald-400':'bg-white/5 text-zinc-500'}`}>{isSaving?'Saving…':isEnabled?'ON · Visible':'OFF · Hidden'}</span><a href={`/services/${service.slug}`} className="text-xs font-bold text-orange-400 hover:text-orange-300">View public page</a></div></div><Switch checked={isEnabled} onCheckedChange={(next)=>void toggle(service.slug,next)} disabled={saving!==null} className="data-checked:bg-emerald-500 data-unchecked:bg-zinc-700" aria-label={`Turn ${service.label} ${isEnabled?'off':'on'}`}/></div></article>;})}</div></>;
}

function ContentPanel({data,onSaved,onError}:{data:Data;onSaved:()=>Promise<void>;onError:(e:string)=>void}){const existing=useMemo(()=>Object.fromEntries(data.content.map(i=>[i.key,i])),[data]);const settings=useMemo(()=>Object.fromEntries(data.settings.map(i=>[i.key,i.value])),[data]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();onError('');const form=new FormData(e.currentTarget);const items=fields.map(([key,,,dka,den])=>({key,value_ka:String(form.get(`${key}_ka`)||dka),value_en:String(form.get(`${key}_en`)||den)}));const values={phone:form.get('phone'),phone_welding:form.get('phone_welding'),phone_electrical:form.get('phone_electrical'),phone_laser_cutting:form.get('phone_laser_cutting'),phone_excavator:form.get('phone_excavator'),phone_towing:form.get('phone_towing'),phone_diagnostics:form.get('phone_diagnostics'),facebook:form.get('facebook'),map_url:form.get('map_url'),hours:form.get('hours'),location:form.get('location')};try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_content',items})});await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values})});await onSaved();}catch(err){onError(err instanceof Error?err.message:'Could not save content.');}}
  return <form onSubmit={submit}><PanelTitle icon={LayoutDashboard} title="Website content" text="Edit the Georgian and English homepage text and business details."/><section className="mt-8 grid gap-5 xl:grid-cols-2">{fields.map(([key,labelKa,labelEn,dka,den])=><div key={key} className="rounded-2xl border border-white/10 bg-[#111214] p-5"><h3 className="mb-4 font-bold">{labelEn}</h3><label className="block"><span className="mb-2 block text-xs font-bold text-orange-400">ქართული</span><textarea name={`${key}_ka`} defaultValue={existing[key]?.value_ka||dka} rows={key.includes('text')||key==='hero_lead'?4:2} className="w-full resize-y rounded-xl border border-white/10 bg-black/25 p-3 outline-none focus:border-orange-500"/></label><label className="mt-4 block"><span className="mb-2 block text-xs font-bold text-zinc-400">English</span><textarea name={`${key}_en`} defaultValue={existing[key]?.value_en||den} rows={key.includes('text')||key==='hero_lead'?4:2} className="w-full resize-y rounded-xl border border-white/10 bg-black/25 p-3 outline-none focus:border-orange-500"/></label></div>)}</section><section className="mt-6 rounded-2xl border border-white/10 bg-[#111214] p-5"><h3 className="mb-5 text-lg font-black">Business details</h3><div className="grid gap-4 md:grid-cols-2"><Input name="phone" label="Main phone / WhatsApp" defaultValue={settings.phone||'+995574814088'}/><Input name="facebook" label="Facebook URL" defaultValue={settings.facebook||'https://www.facebook.com/profile.php?id=61589481147761'}/><Input name="map_url" label="Google Maps URL" defaultValue={settings.map_url||'https://maps.app.goo.gl/7jSzVvmDWJkMUuYNA'}/><Input name="hours" label="Working hours" defaultValue={settings.hours||'10:00–23:00'}/><Input name="location" label="Location" defaultValue={settings.location||'Gori, Georgia'}/></div></section><section className="mt-6 rounded-2xl border border-white/10 bg-[#111214] p-5"><h3 className="mb-2 text-lg font-black">Service contact numbers</h3><p className="mb-5 text-sm text-zinc-500">Each service page uses its own phone and WhatsApp number. Empty fields use the service default.</p><div className="grid gap-4 md:grid-cols-2">{servicePhoneFields.map(([name,label,fallback])=><Input key={name} name={name} label={label} defaultValue={settings[name]||fallback} required={false}/>)}</div></section><button className="sticky bottom-5 mt-6 flex h-13 items-center gap-2 rounded-full bg-orange-500 px-7 font-black text-black shadow-xl hover:bg-orange-400"><Save className="h-5 w-5"/>Save all changes</button></form>;
}

function MediaPanel({data,onSaved,onError}:{data:Data;onSaved:(m:string)=>Promise<void>;onError:(e:string)=>void}){
  const settings=Object.fromEntries(data.settings.map(i=>[i.key,i.value]));
  const[selectedGallery,setSelectedGallery]=useState<ServiceSlug>('welding');
  const[savingBuiltIn,setSavingBuiltIn]=useState<string|null>(null);
  const selectedService=serviceOptions.find(service=>service.slug===selectedGallery)!;
  const galleryItems=data.media.filter(m=>m.gallery===selectedGallery).sort((a,b)=>Number(a.gallery_order??0)-Number(b.gallery_order??0));
  const hiddenBuiltInPhotos=new Set(parseHiddenBuiltInPhotos(settings.hidden_builtin_photos));
  const builtInItems=builtInServicePhotos[selectedGallery];
  const visibleBuiltInItems=builtInItems.filter(item=>!hiddenBuiltInPhotos.has(item.src));
  const visiblePhotoCount=visibleBuiltInItems.length+galleryItems.length;
  const galleryLabel=(gallery:ServiceSlug|null)=>serviceOptions.find(service=>service.slug===gallery)?.label??'Not in a gallery';
  async function saveGallery(ids:string[],message:string){try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_gallery',gallery:selectedGallery,ids})});await onSaved(message);}catch(err){onError(err instanceof Error?err.message:'Could not update gallery.');}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();onError('');const form=new FormData(e.currentTarget);const gallery=String(form.get('gallery')||selectedGallery) as ServiceSlug;const addToGallery=form.get('addToGallery')==='true';try{await api('/api/admin/media',{method:'POST',body:form});setSelectedGallery(gallery);e.currentTarget.reset();await onSaved(addToGallery?`Image uploaded to the ${galleryLabel(gallery)} gallery`:'Image uploaded');}catch(err){onError(err instanceof Error?err.message:'Upload failed.');}}
  async function use(id:string,type:'logo'|'hero'){try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values:{[`${type}_media_id`]:id}})});await onSaved(`${type==='logo'?'Logo':'Hero image'} updated`);}catch(err){onError(err instanceof Error?err.message:'Could not update image.');}}
  async function assignGallery(id:string,gallery:ServiceSlug|null){try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign_gallery',mediaId:id,gallery})});await onSaved(gallery?`Image moved to the ${galleryLabel(gallery)} gallery`:'Image removed from public galleries');}catch(err){onError(err instanceof Error?err.message:'Could not update image gallery.');}}
  async function removeFromGallery(id:string){await assignGallery(id,null);}
  async function move(id:string,direction:-1|1){const ids=galleryItems.map(item=>item.id);const index=ids.indexOf(id);const next=index+direction;if(index<0||next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];await saveGallery(ids,'Gallery order updated');}
  async function remove(id:string){if(!confirm('Delete this image permanently?'))return;try{await api(`/api/admin/media?id=${encodeURIComponent(id)}`,{method:'DELETE'});await onSaved('Image deleted');}catch(err){onError(err instanceof Error?err.message:'Could not delete image.');}}
  async function setBuiltInVisibility(src:string,visible:boolean){const next=visible?[...hiddenBuiltInPhotos].filter(item=>item!==src):[...hiddenBuiltInPhotos,src];setSavingBuiltIn(src);onError('');try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values:{hidden_builtin_photos:JSON.stringify(next)}})});await onSaved(visible?'Original photo restored':'Original photo removed from the service');}catch(err){onError(err instanceof Error?err.message:'Could not update original photo.');}finally{setSavingBuiltIn(null);}}
  return <><PanelTitle icon={FileImage} title="Service photos" text="Choose a service, then upload, arrange, or delete its photos."/>
    <nav aria-label="Choose service gallery" className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{serviceOptions.map(service=>{const count=builtInServicePhotos[service.slug].filter(item=>!hiddenBuiltInPhotos.has(item.src)).length+data.media.filter(item=>item.gallery===service.slug).length;const active=service.slug===selectedGallery;return <button key={service.slug} type="button" onClick={()=>setSelectedGallery(service.slug)} aria-pressed={active} className={`rounded-2xl border p-4 text-left transition ${active?'border-orange-500 bg-orange-500 text-black':'border-white/10 bg-[#111214] text-white hover:border-orange-500/40'}`}><strong className="block text-sm">{service.label}</strong><span className={`mt-1 block text-xs ${active?'text-black/65':'text-zinc-500'}`}>{service.labelKa}</span><span className={`mt-3 block text-xs font-black ${active?'text-black':'text-orange-400'}`}>{count} visible photo{count===1?'':'s'}</span></button>;})}</nav>
    <section className="mt-6 overflow-hidden rounded-2xl border border-orange-500/30 bg-[#111214]"><div className="border-b border-white/10 bg-orange-500/[.06] p-5 sm:p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-orange-400">Selected service</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">{selectedService.label}</h2><p className="text-sm text-zinc-500">{selectedService.labelKa}</p></div><a href={`/services/${selectedGallery}`} className="rounded-full border border-white/10 px-4 py-2 text-sm font-bold text-orange-400 hover:border-orange-500/50">View public gallery</a></div></div>
      <form onSubmit={upload} className="border-b border-white/10 p-5 sm:p-6"><input type="hidden" name="gallery" value={selectedGallery}/><input type="hidden" name="addToGallery" value="true"/><div className="grid gap-4 xl:grid-cols-[1.1fr_1fr_1fr_auto] xl:items-end"><label><span className="mb-2 block text-sm font-bold text-orange-400">Upload photo to {selectedService.label}</span><input required name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="block w-full text-sm text-zinc-400 file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-4 file:py-2 file:text-white"/></label><Input name="altKa" label="Georgian description" placeholder="შესრულებული სამუშაო"/><Input name="altEn" label="English description" placeholder="Completed project"/><button className="flex h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-6 font-black text-black"><ImagePlus className="h-5 w-5"/>Upload photo</button></div></form>
      <div className="p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><h3 className="text-lg font-black">All {selectedService.label} photos</h3><p className="mt-1 text-sm text-zinc-500">Original website photos and administrator uploads are shown together here.</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-sm font-black text-zinc-300">{visiblePhotoCount} visible</span></div>
        {builtInItems.length>0&&<div className="mt-6"><div className="mb-3 flex items-center justify-between gap-4"><h4 className="font-black">Original website photos</h4><span className="text-xs font-bold text-zinc-500">{visibleBuiltInItems.length} of {builtInItems.length} visible</span></div><div className="flex gap-4 overflow-x-auto pb-3">{builtInItems.map(item=>{const isHidden=hiddenBuiltInPhotos.has(item.src);const isSaving=savingBuiltIn===item.src;return <article key={item.src} className={`w-56 shrink-0 overflow-hidden rounded-xl border bg-black/25 ${isHidden?'border-white/5 opacity-60':'border-orange-500/25'}`}><div className="relative"><img src={item.src} alt={item.en} className={`aspect-video w-full object-cover ${isHidden?'grayscale':''}`}/><span className={`absolute left-2 top-2 rounded-full px-2.5 py-1 text-[11px] font-black ${isHidden?'bg-zinc-800 text-zinc-300':'bg-orange-500 text-black'}`}>{isHidden?'HIDDEN':'ORIGINAL'}</span></div><div className="p-3"><strong className="block min-h-10 text-sm leading-5">{item.en}</strong><p className="mt-1 line-clamp-2 text-xs text-zinc-500">{item.ka}</p><button type="button" disabled={savingBuiltIn!==null} onClick={()=>void setBuiltInVisibility(item.src,isHidden)} className={`mt-3 flex w-full items-center justify-center gap-2 rounded-lg px-3 py-2 text-xs font-black disabled:opacity-50 ${isHidden?'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20':'border border-red-500/25 bg-red-500/10 text-red-400 hover:bg-red-500/20'}`}>{isSaving?'Saving…':isHidden?'Restore photo':<><Trash2 className="h-4 w-4"/>Remove from website</>}</button></div></article>;})}</div></div>}
        <div className="mt-6"><div className="mb-3 flex items-center justify-between gap-4"><div><h4 className="font-black">Uploaded photos</h4><p className="mt-1 text-xs text-zinc-500">Use the arrows to change their order after the original photos.</p></div><span className="text-xs font-bold text-zinc-500">{galleryItems.length}</span></div>{galleryItems.length>0?<div className="flex gap-4 overflow-x-auto pb-3">{galleryItems.map((m,index)=><article key={m.id} className="w-56 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-black/25"><img src={m.url} alt={m.alt_en||m.filename} className="aspect-video w-full object-cover"/><div className="p-3"><strong className="block truncate text-sm">{m.alt_en||m.filename}</strong><div className="mt-3 flex items-center gap-2"><button type="button" onClick={()=>move(m.id,-1)} disabled={index===0} className="grid h-8 w-8 place-items-center rounded-lg bg-white/8 disabled:opacity-25" aria-label="Move photo earlier"><ArrowUp className="h-4 w-4"/></button><button type="button" onClick={()=>move(m.id,1)} disabled={index===galleryItems.length-1} className="grid h-8 w-8 place-items-center rounded-lg bg-white/8 disabled:opacity-25" aria-label="Move photo later"><ArrowDown className="h-4 w-4"/></button><button type="button" onClick={()=>removeFromGallery(m.id)} className="ml-auto text-xs font-bold text-zinc-400 hover:text-white">Unlink</button></div><button type="button" onClick={()=>remove(m.id)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-2 text-xs font-black text-red-400 hover:bg-red-500/20"><Trash2 className="h-4 w-4"/>Delete photo</button></div></article>)}</div>:<p className="rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-500">No administrator uploads for this service yet.</p>}</div>
        {builtInItems.length===0&&galleryItems.length===0&&<p className="mt-5 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-zinc-500">No photos in this service. Upload the first photo above.</p>}
      </div></section>
    <section className="mt-10"><div><h2 className="text-2xl font-black">All uploaded images & branding</h2><p className="mt-1 text-sm text-zinc-500">Move an image to another service, or use it as the website logo or main image.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.media.map(m=><article key={m.id} className={`overflow-hidden rounded-2xl border bg-[#111214] ${m.gallery?'border-orange-500/45':'border-white/10'}`}><div className="relative aspect-video bg-black"><img src={m.url} alt={m.alt_en||m.filename} className="h-full w-full object-cover"/><div className="absolute left-3 top-3 flex flex-wrap gap-2">{m.gallery&&<span className="rounded-full bg-[#25D366] px-3 py-1 text-xs font-black text-black">{galleryLabel(m.gallery).toUpperCase()}</span>}{(settings.logo_media_id===m.id||settings.hero_media_id===m.id)&&<span className="rounded-full bg-orange-500 px-3 py-1 text-xs font-black text-black">{settings.logo_media_id===m.id?'ACTIVE LOGO':'ACTIVE HERO'}</span>}</div></div><div className="p-4"><strong className="block truncate">{m.filename}</strong><span className="text-xs text-zinc-500">{(m.size/1024/1024).toFixed(2)} MB</span><label className="mt-4 block"><span className="mb-2 block text-xs font-bold text-zinc-400">Service</span><NativeSelect value={m.gallery??''} onChange={(event)=>assignGallery(m.id,event.target.value?event.target.value as ServiceSlug:null)} className="w-full [&_select]:h-10 [&_select]:border-white/10 [&_select]:bg-black/30"><NativeSelectOption value="">Not in a gallery</NativeSelectOption>{serviceOptions.map(service=><NativeSelectOption key={service.slug} value={service.slug}>{service.label}</NativeSelectOption>)}</NativeSelect></label><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>use(m.id,'logo')} className="rounded-lg bg-white/8 px-3 py-2 text-xs font-bold hover:bg-white/15">Use as logo</button><button type="button" onClick={()=>use(m.id,'hero')} className="rounded-lg bg-white/8 px-3 py-2 text-xs font-bold hover:bg-white/15">Use as hero</button><button type="button" onClick={()=>remove(m.id)} className="ml-auto flex items-center gap-2 rounded-lg bg-red-500/10 px-3 py-2 text-xs font-black text-red-400 hover:bg-red-500/20" aria-label="Delete image"><Trash2 className="h-4 w-4"/>Delete</button></div></div></article>)}{data.media.length===0&&<div className="col-span-full rounded-2xl border border-white/10 p-12 text-center text-zinc-500">No uploaded images yet. Choose a service above and upload your first photo.</div>}</div></section></>;
}

function PanelTitle({icon:Icon,title,text}:{icon:React.ComponentType<{className?:string}>;title:string;text:string}){return <div><div className="mb-3 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-500 text-black"><Icon className="h-5 w-5"/></span><h1 className="text-3xl font-black sm:text-4xl">{title}</h1></div><p className="max-w-2xl text-zinc-400">{text}</p></div>}
