'use client';

import { ArrowDown, ArrowLeft, ArrowUp, Check, FileImage, ImagePlus, LayoutDashboard, LogOut, Save, ShieldCheck, Trash2, Users, Wrench } from 'lucide-react';
import Image from 'next/image';
import UsersPanel from '@/components/admin-users';
import { canAccessAdmin } from '@/lib/access';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';

type User = {id:string;email:string;name:string;role:'super_admin'|'admin'|'user';status:'active'|'disabled';googleConnected:boolean;createdAt:number};
type Data = {user:User;content:Array<{key:string;value_ka:string;value_en:string}>;settings:Array<{key:string;value:string}>;media:Array<{id:string;filename:string;content_type:string;size:number;alt_ka:string;alt_en:string;created_at:number;url:string;in_gallery:number;gallery_order:number|null}>};
const fields=[
  ['hero_title_a','მთავარი სათაური — პირველი ხაზი','Hero title — first line','ლითონს ვაძლევთ','We shape metal'],
  ['hero_title_b','მთავარი სათაური — მეორე ხაზი','Hero title — second line','ძლიერ ფორმას.','to last.'],
  ['hero_lead','მთავარი აღწერა','Hero description','ყველა ტიპის შედუღება, ელექტრო მომსახურება, სამრეწველო დანადგარები და ავტომობილის დიაგნოსტიკა — ერთი საიმედო გუნდისგან.','All types of welding, electrical services, industrial equipment and basic car diagnostics — from one reliable team.'],
  ['welding_title','შედუღების სათაური','Welding heading','შედუღება, რომელიც უძლებს დროს','Welding built to stand the test of time'],
  ['welding_text','შედუღების აღწერა','Welding description','ვმუშაობთ როგორც კერძო შეკვეთებზე, ისე სამშენებლო კომპანიებისა და საწარმოებისთვის.','We handle private jobs as well as projects for construction companies and factories.'],
  ['services_title','სერვისების სათაური','Services heading','ყველა სერვისი ერთ სივრცეში','Every service in one place'],
  ['cta_title','კონტაქტის სათაური','Contact heading','გაქვთ სამუშაო? დავიწყოთ საუბარი.','Have a job in mind? Let’s talk.'],
  ['cta_text','კონტაქტის აღწერა','Contact description','გამოგვიგზავნეთ ფოტო ან მოკლე აღწერა WhatsApp-ზე და მიიღეთ სწრაფი პასუხი.','Send a photo or a short description on WhatsApp and get a quick response.'],
] as const;

async function api<T=any>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const result:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Something went wrong.');return result as T;}

export default function AdminDashboard({initialTab='content'}:{initialTab?:'content'|'media'|'users'}){
  const [me,setMe]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<'content'|'media'|'users'>(initialTab);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setError('');try{const auth=await api<{user:User|null}>('/api/auth/me');if(!canAccessAdmin(auth.user)){setMe(null);setData(null);window.location.replace('/login');return;}setMe(auth.user);const admin=await api<Data>('/api/admin');setData(admin);}catch(e){setError(e instanceof Error?e.message:'Could not load admin panel.');}finally{setLoading(false);}},[]);
  useEffect(()=>{if(initialTab!=='users'&&new URLSearchParams(window.location.search).get('tab')==='media')setTab('media');void load();},[load,initialTab]);
  const flash=(message:string)=>{setNotice(message);setTimeout(()=>setNotice(''),3000);};
  if(loading)return <div className="grid min-h-screen place-items-center bg-[#090a0b] text-white"><div className="flex items-center gap-3"><Wrench className="animate-spin text-orange-500"/>Loading admin panel…</div></div>;
  if(!me)return <div className="grid min-h-screen place-items-center bg-[#090a0b] text-white"><a href="/login" className="text-orange-400">Log in to continue</a></div>;
  if(!data)return <div className="grid min-h-screen place-items-center bg-[#090a0b] p-6 text-center text-white"><div><p className="text-red-400">{error||'Could not load dashboard.'}</p><button onClick={load} className="mt-4 rounded-full bg-orange-500 px-6 py-3 font-bold text-black">Try again</button></div></div>;
  return <div className="min-h-screen bg-[#0a0b0d] text-white">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0a0b0d]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><Image src="/logo.jpg" width={46} height={46} alt="Napertskala" className="h-11 w-11 rounded-full object-cover"/><div><strong className="block">Napertskala</strong><span className="text-xs text-zinc-500">Content management</span></div></div><div className="flex items-center gap-3"><a href="/" className="hidden items-center gap-2 text-sm text-zinc-400 hover:text-white sm:flex"><ArrowLeft className="h-4 w-4"/>View site</a><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.replace('/');}} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-zinc-400 hover:text-white" aria-label="Log out"><LogOut className="h-4 w-4"/></button></div></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[260px_1fr]">
      <aside className="border-b border-white/10 p-4 lg:min-h-[calc(100vh-80px)] lg:border-b-0 lg:border-r lg:p-6"><div className="flex gap-2 overflow-x-auto lg:block lg:space-y-2">{([['content',LayoutDashboard,'Content','/admin'],['media',FileImage,'Images','/admin?tab=media'],['users',Users,'Users','/admin/users']] as const).filter(([id])=>id!=='users'||me.role==='super_admin').map(([id,Icon,label,href])=><a key={id} href={href} aria-current={tab===id?'page':undefined} className={`flex min-w-max items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold lg:w-full ${tab===id?'bg-orange-500 text-black':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-5 w-5"/>{label}</a>)}</div><div className="mt-8 hidden rounded-2xl border border-white/10 bg-white/[.03] p-4 lg:block"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-orange-500/15 text-orange-400"><ShieldCheck className="h-5 w-5"/></span><div className="min-w-0"><strong className="block truncate text-sm">{me.name}</strong><span className="text-xs text-zinc-500">{me.role==='super_admin'?'Super Admin':'Admin'}</span></div></div></div></aside>
      <main className="min-w-0 p-5 sm:p-8 lg:p-10">{notice&&<div className="fixed right-5 top-24 z-50 flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-3 font-bold text-black shadow-xl"><Check className="h-5 w-5"/>{notice}</div>}{error&&<div className="mb-5 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
        {tab==='content'&&<ContentPanel data={data} onSaved={async()=>{flash('Content saved');await load();}} onError={setError}/>} {tab==='media'&&<MediaPanel data={data} onSaved={async(m)=>{flash(m);await load();}} onError={setError}/>} {tab==='users'&&me.role==='super_admin'&&<UsersPanel/>}
      </main>
    </div>
  </div>;
}

function Input({label,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="block"><span className="mb-2 block text-xs font-bold text-zinc-400">{label}</span><input required {...props} className="h-12 w-full rounded-xl border border-white/10 bg-black/30 px-4 outline-none transition focus:border-orange-500"/></label>}

function ContentPanel({data,onSaved,onError}:{data:Data;onSaved:()=>Promise<void>;onError:(e:string)=>void}){const existing=useMemo(()=>Object.fromEntries(data.content.map(i=>[i.key,i])),[data]);const settings=useMemo(()=>Object.fromEntries(data.settings.map(i=>[i.key,i.value])),[data]);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();onError('');const form=new FormData(e.currentTarget);const items=fields.map(([key,,,dka,den])=>({key,value_ka:String(form.get(`${key}_ka`)||dka),value_en:String(form.get(`${key}_en`)||den)}));const values={phone:form.get('phone'),facebook:form.get('facebook'),hours:form.get('hours'),location:form.get('location')};try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_content',items})});await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values})});await onSaved();}catch(err){onError(err instanceof Error?err.message:'Could not save content.');}}
  return <form onSubmit={submit}><PanelTitle icon={LayoutDashboard} title="Website content" text="Edit the Georgian and English homepage text and business details."/><section className="mt-8 grid gap-5 xl:grid-cols-2">{fields.map(([key,labelKa,labelEn,dka,den])=><div key={key} className="rounded-2xl border border-white/10 bg-[#111214] p-5"><h3 className="mb-4 font-bold">{labelEn}</h3><label className="block"><span className="mb-2 block text-xs font-bold text-orange-400">ქართული</span><textarea name={`${key}_ka`} defaultValue={existing[key]?.value_ka||dka} rows={key.includes('text')||key==='hero_lead'?4:2} className="w-full resize-y rounded-xl border border-white/10 bg-black/25 p-3 outline-none focus:border-orange-500"/></label><label className="mt-4 block"><span className="mb-2 block text-xs font-bold text-zinc-400">English</span><textarea name={`${key}_en`} defaultValue={existing[key]?.value_en||den} rows={key.includes('text')||key==='hero_lead'?4:2} className="w-full resize-y rounded-xl border border-white/10 bg-black/25 p-3 outline-none focus:border-orange-500"/></label></div>)}</section><section className="mt-6 rounded-2xl border border-white/10 bg-[#111214] p-5"><h3 className="mb-5 text-lg font-black">Business details</h3><div className="grid gap-4 md:grid-cols-2"><Input name="phone" label="Phone / WhatsApp" defaultValue={settings.phone||'+995574814088'}/><Input name="facebook" label="Facebook URL" defaultValue={settings.facebook||'https://www.facebook.com/profile.php?id=61589481147761'}/><Input name="hours" label="Working hours" defaultValue={settings.hours||'10:00–23:00'}/><Input name="location" label="Location" defaultValue={settings.location||'Gori, Georgia'}/></div></section><button className="sticky bottom-5 mt-6 flex h-13 items-center gap-2 rounded-full bg-orange-500 px-7 font-black text-black shadow-xl hover:bg-orange-400"><Save className="h-5 w-5"/>Save all changes</button></form>;
}

function MediaPanel({data,onSaved,onError}:{data:Data;onSaved:(m:string)=>Promise<void>;onError:(e:string)=>void}){
  const settings=Object.fromEntries(data.settings.map(i=>[i.key,i.value]));
  const galleryItems=data.media.filter(m=>Boolean(Number(m.in_gallery))).sort((a,b)=>Number(a.gallery_order??0)-Number(b.gallery_order??0));
  async function saveGallery(ids:string[],message:string){try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_gallery',ids})});await onSaved(message);}catch(err){onError(err instanceof Error?err.message:'Could not update gallery.');}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();onError('');try{await api('/api/admin/media',{method:'POST',body:new FormData(e.currentTarget)});e.currentTarget.reset();await onSaved('Image uploaded and added to the welding gallery');}catch(err){onError(err instanceof Error?err.message:'Upload failed.');}}
  async function use(id:string,type:'logo'|'hero'){try{await api('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save_settings',values:{[`${type}_media_id`]:id}})});await onSaved(`${type==='logo'?'Logo':'Hero image'} updated`);}catch(err){onError(err instanceof Error?err.message:'Could not update image.');}}
  async function toggleGallery(id:string,inGallery:boolean){const ids=galleryItems.map(item=>item.id);await saveGallery(inGallery?ids.filter(item=>item!==id):[...ids,id],inGallery?'Image removed from welding gallery':'Image added to welding gallery');}
  async function move(id:string,direction:-1|1){const ids=galleryItems.map(item=>item.id);const index=ids.indexOf(id);const next=index+direction;if(index<0||next<0||next>=ids.length)return;[ids[index],ids[next]]=[ids[next],ids[index]];await saveGallery(ids,'Gallery order updated');}
  async function remove(id:string){if(!confirm('Delete this image permanently?'))return;try{await api(`/api/admin/media?id=${encodeURIComponent(id)}`,{method:'DELETE'});await onSaved('Image deleted');}catch(err){onError(err instanceof Error?err.message:'Could not delete image.');}}
  return <><PanelTitle icon={FileImage} title="Images & welding gallery" text="Upload photos, add them to the public welding gallery, change their order, or choose a logo and hero image."/>
    <form onSubmit={upload} className="mt-8 rounded-2xl border border-dashed border-orange-500/35 bg-orange-500/[.06] p-6"><div className="grid gap-4 lg:grid-cols-[1fr_1fr_1fr_auto] lg:items-end"><label><span className="mb-2 block text-xs font-bold text-orange-400">Image file</span><input required name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="block w-full text-sm text-zinc-400 file:mr-3 file:rounded-lg file:border-0 file:bg-white/10 file:px-4 file:py-2 file:text-white"/></label><Input name="altKa" label="Georgian image description" placeholder="შედუღების სამუშაო"/><Input name="altEn" label="English image description" placeholder="Welding project"/><button className="flex h-12 items-center justify-center gap-2 rounded-xl bg-orange-500 px-6 font-black text-black"><ImagePlus className="h-5 w-5"/>Upload</button></div><label className="mt-4 flex items-center gap-3 text-sm font-bold text-zinc-300"><input name="addToGallery" value="true" type="checkbox" defaultChecked className="h-4 w-4 accent-orange-500"/>Add this photo to the welding service gallery</label></form>
    <section className="mt-8 rounded-2xl border border-white/10 bg-[#111214] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Public welding gallery</h2><p className="mt-1 text-sm text-zinc-500">{galleryItems.length} administrator photo{galleryItems.length===1?'':'s'} added after the 12 original project photos.</p></div><a href="/services/welding" className="rounded-full border border-white/10 px-4 py-2 text-xs font-bold text-orange-400 hover:border-orange-500/50">View gallery</a></div>{galleryItems.length>0?<div className="mt-5 flex gap-4 overflow-x-auto pb-3">{galleryItems.map((m,index)=><article key={m.id} className="w-52 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-black/25"><img src={m.url} alt={m.alt_en||m.filename} className="aspect-video w-full object-cover"/><div className="p-3"><strong className="block truncate text-sm">{m.alt_en||m.filename}</strong><div className="mt-3 flex items-center gap-2"><button onClick={()=>move(m.id,-1)} disabled={index===0} className="grid h-8 w-8 place-items-center rounded-lg bg-white/8 disabled:opacity-25" aria-label="Move photo earlier"><ArrowUp className="h-4 w-4"/></button><button onClick={()=>move(m.id,1)} disabled={index===galleryItems.length-1} className="grid h-8 w-8 place-items-center rounded-lg bg-white/8 disabled:opacity-25" aria-label="Move photo later"><ArrowDown className="h-4 w-4"/></button><button onClick={()=>toggleGallery(m.id,true)} className="ml-auto text-xs font-bold text-red-400">Remove</button></div></div></article>)}</div>:<p className="mt-5 rounded-xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-500">Uploaded gallery photos will appear here. The 12 original project photos remain visible on the public page.</p>}</section>
    <div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{data.media.map(m=><article key={m.id} className={`overflow-hidden rounded-2xl border bg-[#111214] ${Number(m.in_gallery)?'border-orange-500/45':'border-white/10'}`}><div className="relative aspect-video bg-black"><img src={m.url} alt={m.alt_en||m.filename} className="h-full w-full object-cover"/><div className="absolute left-3 top-3 flex flex-wrap gap-2">{Number(m.in_gallery)===1&&<span className="rounded-full bg-[#25D366] px-3 py-1 text-xs font-black text-black">IN WELDING GALLERY</span>}{(settings.logo_media_id===m.id||settings.hero_media_id===m.id)&&<span className="rounded-full bg-orange-500 px-3 py-1 text-xs font-black text-black">{settings.logo_media_id===m.id?'ACTIVE LOGO':'ACTIVE HERO'}</span>}</div></div><div className="p-4"><strong className="block truncate">{m.filename}</strong><span className="text-xs text-zinc-500">{(m.size/1024/1024).toFixed(2)} MB</span><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>toggleGallery(m.id,Boolean(Number(m.in_gallery)))} className={`rounded-lg px-3 py-2 text-xs font-bold ${Number(m.in_gallery)?'bg-red-500/10 text-red-300 hover:bg-red-500/20':'bg-[#25D366]/10 text-[#57e389] hover:bg-[#25D366]/20'}`}>{Number(m.in_gallery)?'Remove from gallery':'Add to welding gallery'}</button><button onClick={()=>use(m.id,'logo')} className="rounded-lg bg-white/8 px-3 py-2 text-xs font-bold hover:bg-white/15">Use as logo</button><button onClick={()=>use(m.id,'hero')} className="rounded-lg bg-white/8 px-3 py-2 text-xs font-bold hover:bg-white/15">Use as hero</button><button onClick={()=>remove(m.id)} className="ml-auto grid h-9 w-9 place-items-center rounded-lg text-red-400 hover:bg-red-500/10" aria-label="Delete image"><Trash2 className="h-4 w-4"/></button></div></div></article>)}{data.media.length===0&&<div className="col-span-full rounded-2xl border border-white/10 p-12 text-center text-zinc-500">No uploaded images yet. Your 12 original welding photos are already active on the public page.</div>}</div></>;
}

function PanelTitle({icon:Icon,title,text}:{icon:React.ComponentType<{className?:string}>;title:string;text:string}){return <div><div className="mb-3 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-500 text-black"><Icon className="h-5 w-5"/></span><h1 className="text-3xl font-black sm:text-4xl">{title}</h1></div><p className="max-w-2xl text-zinc-400">{text}</p></div>}
