'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Globe2, KeyRound, Languages, ShieldCheck } from 'lucide-react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { canAccessAdmin, canSignIn } from '@/lib/access';

const copy = {
  ka: { title: 'შესვლა', lead: 'შედით თქვენი ელფოსტითა და პაროლით ან Google ანგარიშით.', email: 'ელფოსტა', password: 'პაროლი', name: 'სახელი და გვარი', submit: 'შესვლა', busy: 'გთხოვთ, დაელოდოთ…', google: 'შესვლა Google-ით', back: 'მთავარზე დაბრუნება', error: 'შესვლა ვერ მოხერხდა. სცადეთ ხელახლა.', unauthorized: 'ამ ანგარიშს მართვის უფლება არ აქვს.', setupTitle: 'მფლობელის ანგარიშის შექმნა', setupLead: 'მხოლოდ მფლობელისთვის: შეიყვანეთ კერძო დაყენების გასაღები, რომელიც მიიღეთ setup-admin.cmd ბრძანებით.', setupKey: 'დაყენების გასაღები', create: 'მფლობელის ანგარიშის შექმნა', or: 'ან', googleUnavailable: 'Google-ით შესვლა ჯერ არ არის გამართული. გამოიყენეთ ელფოსტა და პაროლი.' },
  en: { title: 'Log in', lead: 'Sign in with your email and password or your Google account.', email: 'Email', password: 'Password', name: 'Full name', submit: 'Log in', busy: 'Please wait…', google: 'Continue with Google', back: 'Back to home', error: 'Sign-in failed. Please try again.', unauthorized: 'This account does not have management access.', setupTitle: 'Create owner account', setupLead: 'Owner only: enter the private setup key generated by setup-admin.cmd.', setupKey: 'Private setup key', create: 'Create owner account', or: 'or', googleUnavailable: 'Google sign-in is not configured yet. Use your email and password.' },
};

export default function LoginForm({ setup = false }: { setup?: boolean }) {
  const [lang, setLang] = useState<'ka' | 'en'>('ka');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [googleError, setGoogleError] = useState('');
  const t = copy[lang];
  useEffect(() => { setGoogleError(new URLSearchParams(window.location.search).get('error') ?? ''); }, []);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true); setError(''); setGoogleError('');
    const form = new FormData(event.currentTarget);
    try {
      const response = await fetch(setup ? '/api/auth/register' : '/api/auth/login', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: form.get('email'), password: form.get('password'), ...(setup ? { name: form.get('name'), setupKey: form.get('setupKey') } : {}) }),
      });
      const result = await response.json().catch(() => ({})) as { error?: string } | null;
      if (!response.ok) throw new Error(result?.error || t.error);
      const sessionResponse = await fetch('/api/auth/me', { cache: 'no-store' });
      const session = sessionResponse.ok ? await sessionResponse.json() as { user?: { role?: unknown; status?: unknown } } | null : null;
      if (!canSignIn(session?.user)) throw new Error(t.error);
      window.location.replace(canAccessAdmin(session?.user) ? '/admin' : '/');
    } catch (cause) { setError(cause instanceof Error ? cause.message : t.error); setBusy(false); }
  }

  const inputClass = 'h-12 rounded-xl bg-black/25 px-4';
  return <main className="relative grid min-h-screen place-items-center bg-[#090a0b] px-5 py-12 text-white">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_10%,rgba(249,115,22,.2),transparent_40%)]" />
    <div className="relative w-full max-w-md">
      <div className="mb-8 flex items-center justify-between gap-3"><a href="/" className="flex items-center gap-3"><Image src="/logo.jpg" alt="Napertskala" width={52} height={52} className="h-13 w-13 rounded-full object-cover" /><div><strong className="block text-lg">ნაპერწკალა</strong><span className="text-xs uppercase tracking-widest text-orange-400">Napertskala</span></div></a><Button type="button" variant="outline" className="h-10 rounded-full px-3" onClick={() => setLang(lang === 'ka' ? 'en' : 'ka')} aria-label="Change language"><Languages />{lang === 'ka' ? 'EN' : 'ქარ'}</Button></div>
      <section className="rounded-3xl border border-white/10 bg-[#111214] p-6 shadow-2xl sm:p-8">
        <span className="mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-orange-500 text-black">{setup ? <ShieldCheck /> : <KeyRound />}</span>
        <h1 className="text-3xl font-black">{setup ? t.setupTitle : t.title}</h1><p className="mt-3 text-sm leading-6 text-zinc-400">{setup ? t.setupLead : t.lead}</p>
        {(error || googleError) && <div role="alert" className="mt-5 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error || (googleError === 'google_unavailable' ? t.googleUnavailable : googleError)}</div>}
        <form onSubmit={submit} className="mt-7 space-y-4">
          {setup && <><label className="block text-sm"><span className="mb-2 block text-zinc-400">{t.setupKey}</span><Input name="setupKey" type="password" required autoComplete="off" minLength={32} maxLength={512} className={inputClass} /></label><label className="block text-sm"><span className="mb-2 block text-zinc-400">{t.name}</span><Input name="name" required autoComplete="name" minLength={2} maxLength={120} className={inputClass} /></label></>}
          <label className="block text-sm"><span className="mb-2 block text-zinc-400">{t.email}</span><Input name="email" type="email" required autoComplete="username" maxLength={254} className={inputClass} /></label>
          <label className="block text-sm"><span className="mb-2 block text-zinc-400">{t.password}</span><Input name="password" type="password" required autoComplete={setup ? 'new-password' : 'current-password'} minLength={setup ? 10 : undefined} maxLength={1024} className={inputClass} /></label>
          <Button type="submit" disabled={busy} className="h-12 w-full rounded-xl font-black">{busy ? t.busy : setup ? t.create : t.submit}</Button>
        </form>
        {!setup && <><div className="my-5 flex items-center gap-3 text-xs text-zinc-500"><span className="h-px flex-1 bg-white/10" />{t.or}<span className="h-px flex-1 bg-white/10" /></div><a href="/api/auth/google/start" className="flex h-12 items-center justify-center gap-3 rounded-xl bg-white text-sm font-bold text-zinc-900 hover:bg-zinc-100"><Globe2 className="h-5 w-5" />{t.google}</a></>}
      </section>
      <a href="/" className="mt-6 flex items-center justify-center gap-2 text-sm text-zinc-400 hover:text-orange-400"><ArrowLeft className="h-4 w-4" />{t.back}</a>
    </div>
  </main>;
}
